/* config.h.  Generated by hand.  */
/* Copyright (c) 2022-2023 Benjamin Hampe <benjaminhampe@gmx.de>  */

/* Enable gettext */
#undef ENABLE_NLS

/* Use the Linux SCHED_FIFO scheduler to improve performance. */
#undef ENABLE_REALTIME
//#define ENABLE_REALTIME

/* Gettext package */
#undef GETTEXT_PACKAGE

/* define if the compiler supports basic C++11 syntax */
//#undef HAVE_CXX11
#define HAVE_CXX11

/* Define to 1 if you have the <dlfcn.h> header file. */
#undef HAVE_DLFCN_H

/* Define to 1 if you have the <inttypes.h> header file. */
//#undef HAVE_INTTYPES_H
#define HAVE_INTTYPES_H

/* Define to 1 if you have the <jack/midiport.h> header file. */
#undef HAVE_JACK_MIDIPORT_H

/* Define to 1 if you have the <jack/session.h> header file. */
#undef HAVE_JACK_SESSION_H

/* Define to 1 if you have the `m' library (-lm). */
//#undef HAVE_LIBM
#define HAVE_LIBM

/* Define to 1 if you have the `pthread' library (-lpthread). */
//#undef HAVE_LIBPTHREAD
#define HAVE_LIBPTHREAD

/* Define to 1 if you have the <memory.h> header file. */
//#undef HAVE_MEMORY_H
#define HAVE_MEMORY_H

/* Define to 1 if you have the <stdint.h> header file. */
//#undef HAVE_STDINT_H
#define HAVE_STDINT_H

/* Define to 1 if you have the <stdlib.h> header file. */
//#undef HAVE_STDLIB_H
#define HAVE_STDLIB_H

/* Define to 1 if you have the <strings.h> header file. */
#undef HAVE_STRINGS_H

/* Define to 1 if you have the <string.h> header file. */
//#undef HAVE_STRING_H
#define HAVE_STRING_H

/* Define to 1 if you have the <sys/soundcard.h> header file. */
#undef HAVE_SYS_SOUNDCARD_H

/* Define to 1 if you have the <sys/stat.h> header file. */
#undef HAVE_SYS_STAT_H

/* Define to 1 if you have the <sys/types.h> header file. */
#undef HAVE_SYS_TYPES_H

/* Define to 1 if you have the <unistd.h> header file. */
#undef HAVE_UNISTD_H

/* Define to the sub-directory where libtool stores uninstalled libraries. */
#undef LT_OBJDIR

/* Name of package */
//#undef PACKAGE
#define PACKAGE "Name of Package"

/* Define to the address where bug reports for this package should be sent. */
#undef PACKAGE_BUGREPORT

/* Define to the full name of this package. */
//#undef PACKAGE_NAME
#define PACKAGE_NAME "AMSynth 2023 | Benjamin Hampe, Nick Dowell"

/* Define to the full name and version of this package. */
//#undef PACKAGE_STRING
#define PACKAGE_STRING "Benni's AMSynth Windows64 Port2"

/* Define to the one symbol short name of this package. */
#undef PACKAGE_TARNAME

/* Define to the home page for this package. */
#undef PACKAGE_URL

/* Define to the version of this package. */
#undef PACKAGE_VERSION

/* Define to 1 if you have the ANSI C header files. */
#undef STDC_HEADERS

/* Version number of package */
#undef VERSION

/* Use this optional package */
#undef WITH_ALSA

/* Build GUI */
//#undef WITH_GUI
#define WITH_GUI

/* Use this optional package */
#undef WITH_JACK

/* Use this optional package */
#undef WITH_LASH

/* Build NSM support */
#undef WITH_NSM

/* Use this optional package */
#undef WITH_OSS
