set(PLG_SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}/src)
set(PLG_SOURCES
    ${PLG_SOURCE_DIR}/JucePluginConfig.h
    ${PLG_SOURCE_DIR}/JuceHeader.h
    ${PLG_SOURCE_DIR}/assets/OdinAssets.h
    ${PLG_SOURCE_DIR}/assets/OdinAssets.cpp
    ${PLG_SOURCE_DIR}/AudioParameterConnections.h
    ${PLG_SOURCE_DIR}/AudioValueTree.h
    ${PLG_SOURCE_DIR}/AudioVarDeclarations.h
    ${PLG_SOURCE_DIR}/ConfigFileManager.cpp
    ${PLG_SOURCE_DIR}/ConfigFileManager.h
    ${PLG_SOURCE_DIR}/GeneratedAudioValueCode.h
    ${PLG_SOURCE_DIR}/GlobalIncludes.h
    ${PLG_SOURCE_DIR}/OdinTreeListener.h
    ${PLG_SOURCE_DIR}/PluginEditor.cpp
    ${PLG_SOURCE_DIR}/PluginEditor.h
    ${PLG_SOURCE_DIR}/PluginProcessor.cpp
    ${PLG_SOURCE_DIR}/PluginProcessor.h
    ${PLG_SOURCE_DIR}/PluginProcessorConstructor.cpp
    ${PLG_SOURCE_DIR}/PluginProcessorMidi.cpp
    ${PLG_SOURCE_DIR}/PluginProcessorMigratePatch.cpp
    ${PLG_SOURCE_DIR}/PluginProcessorMisc.cpp
    ${PLG_SOURCE_DIR}/PluginProcessorNonAudioParams.cpp
    ${PLG_SOURCE_DIR}/PluginProcessorProcess.cpp
    ${PLG_SOURCE_DIR}/PluginProcessorReadPatch.cpp
    ${PLG_SOURCE_DIR}/PluginProcessorSetModPointers.cpp
    ${PLG_SOURCE_DIR}/PluginProcessorValueChange.cpp
    ${PLG_SOURCE_DIR}/ProcessorInitializerList.h
    ${PLG_SOURCE_DIR}/Utilities.cpp
    ${PLG_SOURCE_DIR}/Utilities.h
  # ${PLG_SOURCE_DIR}/audio
    ${PLG_SOURCE_DIR}/audio/ADSR.cpp
    ${PLG_SOURCE_DIR}/audio/ADSR.h
    ${PLG_SOURCE_DIR}/audio/Amplifier.cpp
    ${PLG_SOURCE_DIR}/audio/Amplifier.h
    ${PLG_SOURCE_DIR}/audio/ImpulseResponseCreator.cpp
    ${PLG_SOURCE_DIR}/audio/ImpulseResponseCreator.h
    ${PLG_SOURCE_DIR}/audio/OdinConstants.h
    ${PLG_SOURCE_DIR}/audio/Voice.h
  # ${PLG_SOURCE_DIR}/audio/Filters
    ${PLG_SOURCE_DIR}/audio/Filters/BiquadAllpass.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/BiquadAllpass.h
    ${PLG_SOURCE_DIR}/audio/Filters/BiquadEQ.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/BiquadEQ.h
    ${PLG_SOURCE_DIR}/audio/Filters/BiquadFilter.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/BiquadFilter.h
    ${PLG_SOURCE_DIR}/audio/Filters/BiquadResonator.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/BiquadResonator.h
    ${PLG_SOURCE_DIR}/audio/Filters/CombFilter.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/CombFilter.h
    ${PLG_SOURCE_DIR}/audio/Filters/DCBlockingFilter.h
    ${PLG_SOURCE_DIR}/audio/Filters/DiodeFilter.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/DiodeFilter.h
    ${PLG_SOURCE_DIR}/audio/Filters/FormantFilter.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/FormantFilter.h
    ${PLG_SOURCE_DIR}/audio/Filters/Korg35Filter.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/Korg35Filter.h
    ${PLG_SOURCE_DIR}/audio/Filters/LadderFilter.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/LadderFilter.h
    ${PLG_SOURCE_DIR}/audio/Filters/OdinFilterBase.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/OdinFilterBase.h
    ${PLG_SOURCE_DIR}/audio/Filters/SEMFilter12.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/SEMFilter12.h
    ${PLG_SOURCE_DIR}/audio/Filters/VAOnePoleFilter.cpp
    ${PLG_SOURCE_DIR}/audio/Filters/VAOnePoleFilter.h
  # ${PLG_SOURCE_DIR}/audio/FX
    ${PLG_SOURCE_DIR}/audio/FX/Bitcrusher.cpp
    ${PLG_SOURCE_DIR}/audio/FX/Bitcrusher.h
    ${PLG_SOURCE_DIR}/audio/FX/Chorus.cpp
    ${PLG_SOURCE_DIR}/audio/FX/Chorus.h
    ${PLG_SOURCE_DIR}/audio/FX/Delay.cpp
    ${PLG_SOURCE_DIR}/audio/FX/Delay.h
    ${PLG_SOURCE_DIR}/audio/FX/FeedbackDelayNetwork.cpp
    ${PLG_SOURCE_DIR}/audio/FX/FeedbackDelayNetwork.h
    ${PLG_SOURCE_DIR}/audio/FX/Flanger.cpp
    ${PLG_SOURCE_DIR}/audio/FX/Flanger.h
    ${PLG_SOURCE_DIR}/audio/FX/IntegerDelayLine.cpp
    ${PLG_SOURCE_DIR}/audio/FX/IntegerDelayLine.h
    ${PLG_SOURCE_DIR}/audio/FX/OversamplingDistortion.cpp
    ${PLG_SOURCE_DIR}/audio/FX/OversamplingDistortion.h
    ${PLG_SOURCE_DIR}/audio/FX/ParametricEQ.cpp
    ${PLG_SOURCE_DIR}/audio/FX/ParametricEQ.h
    ${PLG_SOURCE_DIR}/audio/FX/Phaser.cpp
    ${PLG_SOURCE_DIR}/audio/FX/Phaser.h
    ${PLG_SOURCE_DIR}/audio/FX/RingModulator.cpp
    ${PLG_SOURCE_DIR}/audio/FX/RingModulator.h
    ${PLG_SOURCE_DIR}/audio/FX/SurgeReverb.cpp
    ${PLG_SOURCE_DIR}/audio/FX/SurgeReverb.h
    ${PLG_SOURCE_DIR}/audio/FX/ZitaReverb.cpp
    ${PLG_SOURCE_DIR}/audio/FX/ZitaReverb.h
  # ${PLG_SOURCE_DIR}/audio/Oscillators
    ${PLG_SOURCE_DIR}/audio/Oscillators/AnalogOscillator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/AnalogOscillator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/ChiptuneArpeggiator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/ChiptuneArpeggiator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/ChiptuneOscillator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/ChiptuneOscillator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/DriftGenerator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/DriftGenerator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/FMOscillator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/FMOscillator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/LFO.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/LFO.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/MultiOscillator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/MultiOscillator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/NoiseOscillator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/NoiseOscillator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Oscillator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/Oscillator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/PitchShiftTable.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/PMCarrierOsc.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/PMOscillator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/PMOscillator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/VectorOscillator.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/VectorOscillator.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/WavetableCoefficients.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/WavetableContainer.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/WavetableContainer.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/WavetableOsc1D.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/WavetableOsc1D.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/WavetableOsc2D.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/WavetableOsc2D.h
  # ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/WavetableMappings.h
  # ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive10.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive11.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive12.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive13.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive14.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive15.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive16.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive7.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Additive9.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_birds_0004.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_birds_0010.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_birds_0011.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_birds_0014.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_bitreduced_0002.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_bitreduced_0003.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_bitreduced_0006.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_bitreduced_0011.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_fmsynth_0011.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_fmsynth_0032.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_fmsynth_0034.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_fmsynth_0081.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0002.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0010.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0014.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0019.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0020.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0021.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0029.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0032.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0037.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0041.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0047.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0049.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0056.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0064.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0071.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/AKWF_hvoice_0093.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/BagPipe.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/BagPipeMutated1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/BagPipeMutated4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/BagPipeMutated5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/BrokenSine1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/BrokenSine2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/BrokenSine3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/BrokenSine4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Cello1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Cello2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChipSaw.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChipSine.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneCustom1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneCustom2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneCustom3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneCustom4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneCustom5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneCustom6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare12_5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare25.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50Mutated1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50Mutated2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50Mutated3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50Mutated4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50Mutated5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50Mutated6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50Mutated7.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneSquare50Mutated8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/ChiptuneTriangle.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/CTDiverging.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/CTHigh.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/CTHigh2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/CTHigh3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/CTRich.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/CTSoftTune.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSaw.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSawMutated1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSawMutated2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSawMutated3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSawMutated4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSawMutated5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSawMutated6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSawMutated7.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/FatSawMutated8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Glass.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/GlassMutated1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/GlassMutated2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/GlassMutated3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics10.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics11.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics12.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics13.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics14.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics15.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics16.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics7.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Harmonics9.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegAah.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegAdd1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegAdd3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegAdd8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegBags.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegBarbedWire.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegCello.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegHarm2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegMale.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegNoBass.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegOrgan.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegPiano.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegRip2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegSharp.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegToyBox.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LegTriQuad.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOPyramid12.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOPyramid4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOPyramid6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOPyramid8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOSpike.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOSquare12.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOSquare25.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOSquare50.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOStair12.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOStair3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOStair4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOStair6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/LFOStair8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Oboe1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Oboe2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Oboe3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Oboe4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Organ1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Organ2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Organ3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Organ4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/PerlinReplace1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/PerlinReplace2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/PerlinReplace3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/PerlinReplace4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/PerlinReplace5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/PerlinReplace6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/PerlinReplace7.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/PerlinReplace8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Piano1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Piano2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Piano3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Piano4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Rectangular1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Rectangular2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Rectangular3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Rectangular4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Saw.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/SawMutated1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/SawMutated2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/SawMutated3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/SawMutated4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/SawMutated5.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/SawMutated6.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/SawMutated7.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/SawMutated8.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Sine.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Skyline1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Skyline2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Skyline3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Skyline4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Triangle.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Trumpet1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Trumpet2.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Trumpet3.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Trumpet4.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Violin1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Coefficients/Violin2.h
  # ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Tables
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Tables/LFOTableData.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Tables/LFOTableData.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Tables/WavetableData.1.h
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Tables/WavetableData.cpp
    ${PLG_SOURCE_DIR}/audio/Oscillators/Wavetables/Tables/WavetableData.h
  # ${PLG_SOURCE_DIR}/gui
    ${PLG_SOURCE_DIR}/gui/ADSRComponent.cpp
    ${PLG_SOURCE_DIR}/gui/ADSRComponent.h
    ${PLG_SOURCE_DIR}/gui/AmpDistortionFlowComponent.cpp
    ${PLG_SOURCE_DIR}/gui/AmpDistortionFlowComponent.h
    ${PLG_SOURCE_DIR}/gui/ArpComponent.cpp
    ${PLG_SOURCE_DIR}/gui/ArpComponent.h
    ${PLG_SOURCE_DIR}/gui/BPMSelector.h
    ${PLG_SOURCE_DIR}/gui/BrowserEntry.cpp
    ${PLG_SOURCE_DIR}/gui/BrowserEntry.h
    ${PLG_SOURCE_DIR}/gui/ChipdrawWindow.cpp
    ${PLG_SOURCE_DIR}/gui/ChipdrawWindow.h
    ${PLG_SOURCE_DIR}/gui/DelayComponent.cpp
    ${PLG_SOURCE_DIR}/gui/DelayComponent.h
    ${PLG_SOURCE_DIR}/gui/DragButton.h
    ${PLG_SOURCE_DIR}/gui/DrawableSlider.cpp
    ${PLG_SOURCE_DIR}/gui/DrawableSlider.h
    ${PLG_SOURCE_DIR}/gui/FactoryPresetBinaryMapping.h
    ${PLG_SOURCE_DIR}/gui/FactoryPresetNames.h
    ${PLG_SOURCE_DIR}/gui/FilterComponent.cpp
    ${PLG_SOURCE_DIR}/gui/FilterComponent.h
    ${PLG_SOURCE_DIR}/gui/FixedTextGlassDropdown.cpp
    ${PLG_SOURCE_DIR}/gui/FixedTextGlassDropdown.h
    ${PLG_SOURCE_DIR}/gui/FormantSelector.h
    ${PLG_SOURCE_DIR}/gui/FXButtonsSection.h
    ${PLG_SOURCE_DIR}/gui/FXComponent.cpp
    ${PLG_SOURCE_DIR}/gui/FXComponent.h
    ${PLG_SOURCE_DIR}/gui/GlasDisplay.cpp
    ${PLG_SOURCE_DIR}/gui/GlasDisplay.h
    ${PLG_SOURCE_DIR}/gui/GlassDropdown.cpp
    ${PLG_SOURCE_DIR}/gui/GlassDropdown.h
    ${PLG_SOURCE_DIR}/gui/GuiDataEditor.cpp
    ${PLG_SOURCE_DIR}/gui/GuiDataEditor.h
    ${PLG_SOURCE_DIR}/gui/InputField.h
    ${PLG_SOURCE_DIR}/gui/IntegerKnob.cpp
    ${PLG_SOURCE_DIR}/gui/IntegerKnob.h
    ${PLG_SOURCE_DIR}/gui/JsonGuiProvider.cpp
    ${PLG_SOURCE_DIR}/gui/JsonGuiProvider.h
    ${PLG_SOURCE_DIR}/gui/LeftRightButton.cpp
    ${PLG_SOURCE_DIR}/gui/LeftRightButton.h
    ${PLG_SOURCE_DIR}/gui/LFOComponent.cpp
    ${PLG_SOURCE_DIR}/gui/LFOComponent.h
    ${PLG_SOURCE_DIR}/gui/LFODisplayComponent.cpp
    ${PLG_SOURCE_DIR}/gui/LFODisplayComponent.h
    ${PLG_SOURCE_DIR}/gui/LFOPopupLookAndFeel.cpp
    ${PLG_SOURCE_DIR}/gui/LFOPopupLookAndFeel.h
    ${PLG_SOURCE_DIR}/gui/LFOSelectorComponent.cpp
    ${PLG_SOURCE_DIR}/gui/LFOSelectorComponent.h
    ${PLG_SOURCE_DIR}/gui/LiveConstrainer.cpp
    ${PLG_SOURCE_DIR}/gui/LiveConstrainer.h
    ${PLG_SOURCE_DIR}/gui/ModAmountComponent.cpp
    ${PLG_SOURCE_DIR}/gui/ModAmountComponent.h
    ${PLG_SOURCE_DIR}/gui/ModAmountComponentExtended.cpp
    ${PLG_SOURCE_DIR}/gui/ModAmountComponentExtended.h
    ${PLG_SOURCE_DIR}/gui/ModMatrix.cpp
    ${PLG_SOURCE_DIR}/gui/ModMatrix.h
    ${PLG_SOURCE_DIR}/gui/ModMatrixComponent.cpp
    ${PLG_SOURCE_DIR}/gui/ModMatrixComponent.h
    ${PLG_SOURCE_DIR}/gui/NumberSelector.cpp
    ${PLG_SOURCE_DIR}/gui/NumberSelector.h
    ${PLG_SOURCE_DIR}/gui/NumberSelectorWithText.cpp
    ${PLG_SOURCE_DIR}/gui/NumberSelectorWithText.h
    ${PLG_SOURCE_DIR}/gui/OdinArpeggiator.cpp
    ${PLG_SOURCE_DIR}/gui/OdinArpeggiator.h
    ${PLG_SOURCE_DIR}/gui/OdinButton.cpp
    ${PLG_SOURCE_DIR}/gui/OdinButton.h
    ${PLG_SOURCE_DIR}/gui/OdinControlAttachments.cpp
    ${PLG_SOURCE_DIR}/gui/OdinControlAttachments.h
    ${PLG_SOURCE_DIR}/gui/OdinControlBase.h
    ${PLG_SOURCE_DIR}/gui/OdinFeels.h
    ${PLG_SOURCE_DIR}/gui/OdinKnob.cpp
    ${PLG_SOURCE_DIR}/gui/OdinKnob.h
    ${PLG_SOURCE_DIR}/gui/OdinTooltipWindow.h
    ${PLG_SOURCE_DIR}/gui/OscComponent.cpp
    ${PLG_SOURCE_DIR}/gui/OscComponent.h
    ${PLG_SOURCE_DIR}/gui/PatchBrowser.cpp
    ${PLG_SOURCE_DIR}/gui/PatchBrowser.h
    ${PLG_SOURCE_DIR}/gui/PatchBrowserScrollBar.cpp
    ${PLG_SOURCE_DIR}/gui/PatchBrowserScrollBar.h
    ${PLG_SOURCE_DIR}/gui/PatchBrowserSelector.cpp
    ${PLG_SOURCE_DIR}/gui/PatchBrowserSelector.h
    ${PLG_SOURCE_DIR}/gui/PhaserComponent.cpp
    ${PLG_SOURCE_DIR}/gui/PhaserComponent.h
    ${PLG_SOURCE_DIR}/gui/PitchWheel.h
    ${PLG_SOURCE_DIR}/gui/RescaleProgressComponent.cpp
    ${PLG_SOURCE_DIR}/gui/RescaleProgressComponent.h
    ${PLG_SOURCE_DIR}/gui/ResizeDragger.cpp
    ${PLG_SOURCE_DIR}/gui/ResizeDragger.h
    ${PLG_SOURCE_DIR}/gui/ReverbComponent.cpp
    ${PLG_SOURCE_DIR}/gui/ReverbComponent.h
    ${PLG_SOURCE_DIR}/gui/SpecdrawDisplay.cpp
    ${PLG_SOURCE_DIR}/gui/SpecdrawDisplay.h
    ${PLG_SOURCE_DIR}/gui/SpectrumDisplay.cpp
    ${PLG_SOURCE_DIR}/gui/SpectrumDisplay.h
    ${PLG_SOURCE_DIR}/gui/SplineAdComponent.cpp
    ${PLG_SOURCE_DIR}/gui/SplineAdComponent.h
    ${PLG_SOURCE_DIR}/gui/StepComponent.cpp
    ${PLG_SOURCE_DIR}/gui/StepComponent.h
    ${PLG_SOURCE_DIR}/gui/StepLED.h
    ${PLG_SOURCE_DIR}/gui/SyncTimeSelector.cpp
    ${PLG_SOURCE_DIR}/gui/SyncTimeSelector.h
    ${PLG_SOURCE_DIR}/gui/TextLabel.h
    ${PLG_SOURCE_DIR}/gui/TitleButton.cpp
    ${PLG_SOURCE_DIR}/gui/TitleButton.h
    ${PLG_SOURCE_DIR}/gui/TooltipFeels.h
    ${PLG_SOURCE_DIR}/gui/TuningComponent.cpp
    ${PLG_SOURCE_DIR}/gui/TuningComponent.h
    ${PLG_SOURCE_DIR}/gui/UIAssetManager.cpp
    ${PLG_SOURCE_DIR}/gui/UIAssetManager.h
    ${PLG_SOURCE_DIR}/gui/UIAssetsData.cpp
    ${PLG_SOURCE_DIR}/gui/UIAssetsData.h
    ${PLG_SOURCE_DIR}/gui/UIAssetsIndices.h
    ${PLG_SOURCE_DIR}/gui/UIAssetsSize.cpp
    ${PLG_SOURCE_DIR}/gui/UIAssetsSize.h
    ${PLG_SOURCE_DIR}/gui/WavedrawDisplay.cpp
    ${PLG_SOURCE_DIR}/gui/WavedrawDisplay.h
    ${PLG_SOURCE_DIR}/gui/WaveformSelectorComponent.cpp
    ${PLG_SOURCE_DIR}/gui/WaveformSelectorComponent.h
    ${PLG_SOURCE_DIR}/gui/WavetableDisplay.cpp
    ${PLG_SOURCE_DIR}/gui/WavetableDisplay.h
    ${PLG_SOURCE_DIR}/gui/XYPadComponent.cpp
    ${PLG_SOURCE_DIR}/gui/XYPadComponent.h
    ${PLG_SOURCE_DIR}/gui/XYSectionComponent.cpp
    ${PLG_SOURCE_DIR}/gui/XYSectionComponent.h
    # ...and so on
    # PARENT_SCOPE
)