#include "OdinAssets.h"

#include "graphics.cpp"
#include "graphics_animations_knob_4x4_a.cpp"
#include "graphics_animations_knob_5x5_a.cpp"
#include "graphics_animations_knob_6x6_a.cpp"
#include "graphics_animations_knob_6x6_b.cpp"
#include "graphics_animations_knob_8x8_a.cpp"
#include "graphics_animations_knob_8x8_b.cpp"
#include "graphics_animations_wheel.cpp"
#include "graphics_buttons.cpp"
#include "misc.cpp"
#include "soundbanks_factory_presets.cpp"