add_subdirectory(plugin_50_alefsbits)
add_subdirectory(plugin_51_Sickozell)
add_subdirectory(plugin_52_Voxglitch)
add_subdirectory(plugin_53_rcm)
add_subdirectory(plugin_54_Sckitam)
add_subdirectory(plugin_55_Bidoo)
add_subdirectory(plugin_56_EucQuant)
add_subdirectory(plugin_57_Stoermelder-P1)
add_subdirectory(plugin_58_SIM)

