add_subdirectory(plugin_70_ORBsqVi)
add_subdirectory(plugin_71_Prism)
add_subdirectory(plugin_72_Bark)
add_subdirectory(plugin_73_MUS-X)
add_subdirectory(plugin_74_DHE-Modules)
add_subdirectory(plugin_75_Dintree-Virtual)
add_subdirectory(plugin_76_mscHack)
add_subdirectory(plugin_77_Chiptuner)
add_subdirectory(plugin_78_PathSetModules)
add_subdirectory(plugin_79_Eightfold)
