add_subdirectory(plugin_130_acModules)
add_subdirectory(plugin_131_MicMusic)
add_subdirectory(plugin_132_NLNRI)
add_subdirectory(plugin_133_rsbatech)
add_subdirectory(plugin_134_ShaBang)
add_subdirectory(plugin_135_Sparkette)
add_subdirectory(plugin_136_stocaudio)
add_subdirectory(plugin_137_Strums_Mental)
add_subdirectory(plugin_138_unless)
add_subdirectory(plugin_139_Sculpt_O_Sound)
