add_subdirectory(plugin_30_Clonotribe)
add_subdirectory(plugin_31_8Mode)
add_subdirectory(plugin_32_SanguineMutants)
add_subdirectory(plugin_33_Impromptu)
add_subdirectory(plugin_34_ML_modules)
add_subdirectory(plugin_35_MindMeld)
add_subdirectory(plugin_36_FruitsOfKarma)
add_subdirectory(plugin_37_cf)
add_subdirectory(plugin_38_ComputerScare)
add_subdirectory(plugin_39_Cella)
