add_subdirectory(plugin_40_GrandeModular)
add_subdirectory(plugin_41_Ahornberg)
add_subdirectory(plugin_42_Befaco)
add_subdirectory(plugin_43_CountModula)
add_subdirectory(plugin_44_DanT.Synth-2.0.1)
add_subdirectory(plugin_45_LunettaModula)
add_subdirectory(plugin_46_NonlinearCircuits)
add_subdirectory(plugin_47_Ondas)
add_subdirectory(plugin_48_TinyTricks)
add_subdirectory(plugin_49_VenomModules)
