add_subdirectory(plugin_00_Benni)
add_subdirectory(plugin_01_Squinky)
add_subdirectory(plugin_02_OrangeLine)
add_subdirectory(plugin_03_Plurm)
add_subdirectory(plugin_04_StarlingCode)
add_subdirectory(plugin_05_vanTies)
add_subdirectory(plugin_06_minilab3)
add_subdirectory(plugin_07_VsWorld)
add_subdirectory(plugin_08_WavsynModular)
add_subdirectory(plugin_09_WhatTheRack)
