#pragma once

static constexpr float HALF = 0.5f;
static constexpr float ZERO = 0.0f;
static constexpr float ONE = 1.0f;
static constexpr float TWO = 2.0f;

static constexpr float OFF = ZERO;
static constexpr float ON = ONE;
static constexpr float MIN = 0.01f;

enum ParamId {
    PARAM_VCO_OCTAVE_KNOB,
    PARAM_VCA_LEVEL_KNOB,
    PARAM_VCO_WAVEFORM_SWITCH,
    PARAM_RHYTHM_VOLUME_KNOB,
    PARAM_DISTORTION_KNOB,
    PARAM_DELAY_TIME_KNOB,
    PARAM_DELAY_AMOUNT_KNOB,
    PARAM_SNARE_BUTTON,
    PARAM_FLUX_BUTTON,
    PARAM_REC_BUTTON,
    PARAM_VCF_CUTOFF_KNOB,
    PARAM_LFO_RATE_KNOB,
    PARAM_LFO_INTENSITY_KNOB,
    PARAM_NOISE_KNOB,
    PARAM_VCF_PEAK_KNOB,
    PARAM_RIBBON_RANGE_SWITCH,
    PARAM_ENVELOPE_FORM_SWITCH,
    PARAM_LFO_TARGET_SWITCH,
    PARAM_LFO_MODE_SWITCH,
    PARAM_LFO_WAVEFORM_SWITCH,
    PARAM_SEQUENCER_TEMPO_KNOB,
    PARAM_SYNTH_BUTTON,
    PARAM_BASSDRUM_BUTTON,
    PARAM_HIGHHAT_BUTTON,
    PARAM_ACTIVE_STEP_BUTTON,
    PARAM_SEQUENCER_1_BUTTON,
    PARAM_SEQUENCER_2_BUTTON,
    PARAM_SEQUENCER_3_BUTTON,
    PARAM_SEQUENCER_4_BUTTON,
    PARAM_SEQUENCER_5_BUTTON,
    PARAM_SEQUENCER_6_BUTTON,
    PARAM_SEQUENCER_7_BUTTON,
    PARAM_SEQUENCER_8_BUTTON,
    PARAM_PLAY_BUTTON,
    PARAM_GATE_TIME_BUTTON,
    PARAM_ACCENT_GLIDE_KNOB,
    PARAMS_LEN
};

enum InputId {
    INPUT_CV_CONNECTOR,
    INPUT_GATE_CONNECTOR,
    INPUT_AUDIO_CONNECTOR,
    INPUT_SYNC_CONNECTOR,
    INPUT_VCO_OCTAVE_CONNECTOR,
    INPUT_VCF_CUTOFF_CONNECTOR,
    INPUT_VCF_PEAK_CONNECTOR,
    INPUT_VCA_CONNECTOR,
    INPUT_LFO_RATE_CONNECTOR,
    INPUT_LFO_INTENSITY_CONNECTOR,
    INPUT_DISTORTION_CONNECTOR,
    INPUT_DELAY_TIME_CONNECTOR,
    INPUT_DELAY_AMOUNT_CONNECTOR,
    INPUT_NOISE_CONNECTOR,
    INPUT_ACCENT_GLIDE_CONNECTOR,
    INPUTS_LEN
};

enum OutputId {
    OUTPUT_CV_CONNECTOR,
    OUTPUT_GATE_CONNECTOR,
    OUTPUT_AUDIO_CONNECTOR,
    OUTPUT_SYNC_CONNECTOR,
    OUTPUT_SYNTH_CONNECTOR,
    OUTPUT_BASSDRUM_CONNECTOR,
    OUTPUT_SNARE_CONNECTOR,
    OUTPUT_HIHAT_CONNECTOR,
    OUTPUT_LFO_RATE_CONNECTOR,
    OUTPUTS_LEN
};

enum LightId {
    LIGHT_SYNTH,
    LIGHT_BASSDRUM,
    LIGHT_SNARE,
    LIGHT_HIGHHAT,
    LIGHT_FLUX,
    LIGHT_REC,
    LIGHT_PLAY,
    LIGHT_SEQUENCER_1_R,
    LIGHT_SEQUENCER_1_G,
    LIGHT_SEQUENCER_1_B,
    LIGHT_SEQUENCER_2_R,
    LIGHT_SEQUENCER_2_G,
    LIGHT_SEQUENCER_2_B,
    LIGHT_SEQUENCER_3_R,
    LIGHT_SEQUENCER_3_G,
    LIGHT_SEQUENCER_3_B,
    LIGHT_SEQUENCER_4_R,
    LIGHT_SEQUENCER_4_G,
    LIGHT_SEQUENCER_4_B,
    LIGHT_SEQUENCER_5_R,
    LIGHT_SEQUENCER_5_G,
    LIGHT_SEQUENCER_5_B,
    LIGHT_SEQUENCER_6_R,
    LIGHT_SEQUENCER_6_G,
    LIGHT_SEQUENCER_6_B,
    LIGHT_SEQUENCER_7_R,
    LIGHT_SEQUENCER_7_G,
    LIGHT_SEQUENCER_7_B,
    LIGHT_SEQUENCER_8_R,
    LIGHT_SEQUENCER_8_G,
    LIGHT_SEQUENCER_8_B,
    LIGHTS_LEN
};