add_subdirectory(plugin_60_CharredDesert)
add_subdirectory(plugin_61_FrozenWasteland)
add_subdirectory(plugin_62_gtg-rack)
add_subdirectory(plugin_63_DrumKit)
add_subdirectory(plugin_64_RPJ)
add_subdirectory(plugin_65_Meander)
add_subdirectory(plugin_66_AS)
add_subdirectory(plugin_67_dBiz)
add_subdirectory(plugin_68_SubmarineFree)
add_subdirectory(plugin_69_kocmoc)
