set(PLG_SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}/src)
set(PLG_SOURCES
    ${PLG_SOURCE_DIR}/JucePluginConfig.h
    ${PLG_SOURCE_DIR}/JuceHeader.h

    ${PLG_SOURCE_DIR}/Processor.cpp
    ${PLG_SOURCE_DIR}/Processor.h
    ${PLG_SOURCE_DIR}/Editor.cpp
    ${PLG_SOURCE_DIR}/Editor.h
    ${PLG_SOURCE_DIR}/Manta_config.h
    
    ${PLG_SOURCE_DIR}/arch/Conversion.h
    ${PLG_SOURCE_DIR}/arch/FormulaParser.h
    ${PLG_SOURCE_DIR}/arch/FormulaParser2.h
    ${PLG_SOURCE_DIR}/arch/Interpolation.h
    ${PLG_SOURCE_DIR}/arch/Range.h
    ${PLG_SOURCE_DIR}/arch/Smooth.cpp
    ${PLG_SOURCE_DIR}/arch/Smooth.h
    ${PLG_SOURCE_DIR}/arch/State.cpp
    ${PLG_SOURCE_DIR}/arch/State.h

    ${PLG_SOURCE_DIR}/audio/AbsorbProcessor.cpp
    ${PLG_SOURCE_DIR}/audio/AbsorbProcessor.h
    ${PLG_SOURCE_DIR}/audio/AudioUtils.h
    ${PLG_SOURCE_DIR}/audio/AutoGain.h
    ${PLG_SOURCE_DIR}/audio/Bitcrusher.h
    ${PLG_SOURCE_DIR}/audio/DryWetMix.cpp
    ${PLG_SOURCE_DIR}/audio/DryWetMix.h
    ${PLG_SOURCE_DIR}/audio/EnvelopeFollower.cpp
    ${PLG_SOURCE_DIR}/audio/EnvelopeFollower.h
    ${PLG_SOURCE_DIR}/audio/Filter.cpp
    ${PLG_SOURCE_DIR}/audio/Filter.h
    ${PLG_SOURCE_DIR}/audio/LatencyCompensation.cpp
    ${PLG_SOURCE_DIR}/audio/LatencyCompensation.h
    ${PLG_SOURCE_DIR}/audio/Manta.h
    ${PLG_SOURCE_DIR}/audio/Meter.cpp
    ${PLG_SOURCE_DIR}/audio/Meter.h
    ${PLG_SOURCE_DIR}/audio/MIDILearn.cpp
    ${PLG_SOURCE_DIR}/audio/MIDILearn.h
    ${PLG_SOURCE_DIR}/audio/MIDIManager.h
    ${PLG_SOURCE_DIR}/audio/MidSide.cpp
    ${PLG_SOURCE_DIR}/audio/MidSide.h
    ${PLG_SOURCE_DIR}/audio/NullNoiseSynth.h
    ${PLG_SOURCE_DIR}/audio/Oscillator.h
    ${PLG_SOURCE_DIR}/audio/OverdriveReNEO.h
    ${PLG_SOURCE_DIR}/audio/Oversampling.cpp
    ${PLG_SOURCE_DIR}/audio/Oversampling.h
    ${PLG_SOURCE_DIR}/audio/Phasor.h
    ${PLG_SOURCE_DIR}/audio/PitchGlitcher.cpp
    ${PLG_SOURCE_DIR}/audio/PitchGlitcher.h
    ${PLG_SOURCE_DIR}/audio/PRM.cpp
    ${PLG_SOURCE_DIR}/audio/PRM.h
    ${PLG_SOURCE_DIR}/audio/ProcessSuspend.h
    ${PLG_SOURCE_DIR}/audio/Rectifier.h
    ${PLG_SOURCE_DIR}/audio/Resonator.h
    ${PLG_SOURCE_DIR}/audio/SpectroBeam.h
    ${PLG_SOURCE_DIR}/audio/WaveTable.h
    ${PLG_SOURCE_DIR}/audio/WHead.cpp
    ${PLG_SOURCE_DIR}/audio/WHead.h
    ${PLG_SOURCE_DIR}/audio/XenManager.h

    ${PLG_SOURCE_DIR}/gui/Button.cpp
    ${PLG_SOURCE_DIR}/gui/Button.h
    ${PLG_SOURCE_DIR}/gui/ButtonParameterRandomizer.cpp
    ${PLG_SOURCE_DIR}/gui/ButtonParameterRandomizer.h
    ${PLG_SOURCE_DIR}/gui/Comp.cpp
    ${PLG_SOURCE_DIR}/gui/Comp.h
    ${PLG_SOURCE_DIR}/gui/ContextMenu.cpp
    ${PLG_SOURCE_DIR}/gui/ContextMenu.h
    ${PLG_SOURCE_DIR}/gui/EQPad.h
    ${PLG_SOURCE_DIR}/gui/Events.cpp
    ${PLG_SOURCE_DIR}/gui/Events.h
    ${PLG_SOURCE_DIR}/gui/FilterResponseGraph.cpp
    ${PLG_SOURCE_DIR}/gui/FilterResponseGraph.h
    ${PLG_SOURCE_DIR}/gui/FormulaParser.h
    ${PLG_SOURCE_DIR}/gui/GUIParams.cpp
    ${PLG_SOURCE_DIR}/gui/GUIParams.h
    ${PLG_SOURCE_DIR}/gui/HighLevel.cpp
    ${PLG_SOURCE_DIR}/gui/HighLevel.h
    ${PLG_SOURCE_DIR}/gui/KeyboardComp.h
    ${PLG_SOURCE_DIR}/gui/Knob.cpp
    ${PLG_SOURCE_DIR}/gui/Knob.h
    ${PLG_SOURCE_DIR}/gui/Label.cpp
    ${PLG_SOURCE_DIR}/gui/Label.h
    ${PLG_SOURCE_DIR}/gui/Layout.cpp
    ${PLG_SOURCE_DIR}/gui/Layout.h
    ${PLG_SOURCE_DIR}/gui/LogoComp.h
    ${PLG_SOURCE_DIR}/gui/LowLevel.h
    ${PLG_SOURCE_DIR}/gui/MantaComp.h
    ${PLG_SOURCE_DIR}/gui/Menu.cpp
    ${PLG_SOURCE_DIR}/gui/Menu.h
    ${PLG_SOURCE_DIR}/gui/menu.xml
    ${PLG_SOURCE_DIR}/gui/MIDICCMonitor.cpp
    ${PLG_SOURCE_DIR}/gui/MIDICCMonitor.h
    ${PLG_SOURCE_DIR}/gui/MIDIVoicesComp.cpp
    ${PLG_SOURCE_DIR}/gui/MIDIVoicesComp.h
    ${PLG_SOURCE_DIR}/gui/PatchBrowser.h
    ${PLG_SOURCE_DIR}/gui/Shader.cpp
    ${PLG_SOURCE_DIR}/gui/Shader.h
    ${PLG_SOURCE_DIR}/gui/Shared.cpp
    ${PLG_SOURCE_DIR}/gui/Shared.h
    ${PLG_SOURCE_DIR}/gui/SpectroBeamComp.h
    ${PLG_SOURCE_DIR}/gui/SplineEditor.h
    ${PLG_SOURCE_DIR}/gui/TextEditor.cpp
    ${PLG_SOURCE_DIR}/gui/TextEditor.h
    ${PLG_SOURCE_DIR}/gui/Tooltip.cpp
    ${PLG_SOURCE_DIR}/gui/Tooltip.h
    ${PLG_SOURCE_DIR}/gui/TuningEditor.h
    ${PLG_SOURCE_DIR}/gui/Using.h
    ${PLG_SOURCE_DIR}/gui/Utils.cpp
    ${PLG_SOURCE_DIR}/gui/Utils.h
    ${PLG_SOURCE_DIR}/gui/WaveTableDisplay.h

    ${PLG_SOURCE_DIR}/param/Param.cpp
    ${PLG_SOURCE_DIR}/param/Param.h



)