#!/bin/sh
set -e

## Update the system menu entry
[ ! -x /usr/bin/update-menus ] || /usr/bin/update-menus

## Check if yt-dlp is installed at PATH
if command -v yt-dlp >/dev/null 2>&1; then
    printf "\033[32m[INFO] 'yt-dlp' is installed at your system. \033[1m TRYING TO UPDATE yt-dlp...\033[0m\n"
    yt-dlp -U
    [ $? -ne 0 ] && printf "\033[33m\033[1m[WARN] CANNOT UPDATE yt-dlp.\033[0m Mantaine yt-dlp up to date, or consider uninstalling it and get the latest version (for example, you can execute the install_yt-dlp.sh command)...\033[0m\n"
else
    printf "\033[32mTrying to install yt-dlp...\033[0m\n"
    if [ -x /usr/local/bin/install_yt-dlp.sh ]; then
        /usr/local/bin/install_yt-dlp.sh -p "/usr/local/bin/" -y
    else
        printf "\033[31mCANNOT INSTALL yt-dlp FROM PACKAGE\033[0m. Please, install manually later using 'install_yt-dlp.sh' command.\n"
    fi
fi

if ! command -v qjs >/dev/null 2>&1; then
    printf "\033[32mTrying to install QuickJS...\033[0m\n"
    if [ -x /usr/local/bin/install_yt-dlp.sh ]; then
        /usr/local/bin/install_yt-dlp.sh -p "/usr/local/bin/" -j
    else
        printf "\033[31mCANNOT INSTALL QuickJS FROM PACKAGE\033[0m. Please, install manually later using 'install_yt-dlp.sh -j' command.\n"
    fi
fi

nonroot_user=$(logname)   #This is the name of the user that run the "apt install" command

su "$nonroot_user" <<EOF
FLTUBE_USER_CONFIGDIR=\$HOME/.config/fltube
FLTUBE_USERDATA_DIR=\$HOME/.local/share/fltube
FLTUBE_CACHE_DIR=\$HOME/.cache/fltube
YTDLP_USER_CONFIGDIR=\$HOME/.config/yt-dlp
if [ ! -f "\$FLTUBE_USER_CONFIGDIR"/fltube.conf ]; then
    [ ! -d "\$FLTUBE_USER_CONFIGDIR" ] && mkdir -p "\$FLTUBE_USER_CONFIGDIR"
	echo "Creating user configuration file at \$FLTUBE_USER_CONFIGDIR."
	cp /usr/local/etc/fltube/fltube.conf "\$FLTUBE_USER_CONFIGDIR"
fi

if [ ! -e "\$FLTUBE_USERDATA_DIR" ]; then
    echo "Creating userdata directory at \$FLTUBE_USERDATA_DIR."
    mkdir -p "\$FLTUBE_USERDATA_DIR"
fi

if [ ! -e "\$FLTUBE_CACHE_DIR" ]; then
    echo "Creating cache directory at \$FLTUBE_CACHE_DIR."
    mkdir -p "\$FLTUBE_CACHE_DIR"
fi

if [ ! -f "\$YTDLP_USER_CONFIGDIR"/config ]; then
    [ ! -d "\$YTDLP_USER_CONFIGDIR" ] && mkdir -p "\$YTDLP_USER_CONFIGDIR"
	echo "Creating user configuration file for 'yt-dlp' at \$YTDLP_USER_CONFIGDIR."
	cp /tmp/yt-dlp_config "\$YTDLP_USER_CONFIGDIR/config"
fi
EOF

exit 0
