add_subdirectory(plugin_20_ValleyRackFree)
add_subdirectory(plugin_21_AuraAudio)
add_subdirectory(plugin_22_SonusModular)
add_subdirectory(plugin_23_LifeFormModular)
add_subdirectory(plugin_24_FehlerFabrik)
add_subdirectory(plugin_25_Algoritmarte)
add_subdirectory(plugin_26_PotatoChips)
add_subdirectory(plugin_27_FartSynthson)
add_subdirectory(plugin_28_CaptVolt)
add_subdirectory(plugin_29_RigatoniModular)
