#pragma once
#define JUCE_CORE_H_INCLUDED
#define JUCE_MODULE_AVAILABLE_juce_core 1

#include <juce_core/juce_core_common.h>

#include <juce_core/containers/juce_AbstractFifo.h>
#include <juce_core/containers/juce_Array.h>
#include <juce_core/containers/juce_ArrayAllocationBase.h>
#include <juce_core/containers/juce_ArrayBase.h>
#include <juce_core/containers/juce_DynamicObject.h>
#include <juce_core/containers/juce_ElementComparator.h>
#include <juce_core/containers/juce_HashMap.h>
#include <juce_core/containers/juce_LinkedListPointer.h>
#include <juce_core/containers/juce_ListenerList.h>
#include <juce_core/containers/juce_NamedValueSet.h>
#include <juce_core/containers/juce_Optional.h>
#include <juce_core/containers/juce_OwnedArray.h>
#include <juce_core/containers/juce_PropertySet.h>
#include <juce_core/containers/juce_ReferenceCountedArray.h>
#include <juce_core/containers/juce_ScopedValueSetter.h>
#include <juce_core/containers/juce_SingleThreadedAbstractFifo.h>
#include <juce_core/containers/juce_SortedSet.h>
#include <juce_core/containers/juce_SparseSet.h>
#include <juce_core/containers/juce_Variant.h>
#include <juce_core/files/juce_AndroidDocument.h>
#include <juce_core/files/juce_common_MimeTypes.h>
#include <juce_core/files/juce_DirectoryIterator.h>
#include <juce_core/files/juce_File.h>
#include <juce_core/files/juce_FileFilter.h>
#include <juce_core/files/juce_FileInputStream.h>
#include <juce_core/files/juce_FileOutputStream.h>
#include <juce_core/files/juce_FileSearchPath.h>
#include <juce_core/files/juce_MemoryMappedFile.h>
#include <juce_core/files/juce_RangedDirectoryIterator.h>
#include <juce_core/files/juce_TemporaryFile.h>
#include <juce_core/files/juce_WildcardFileFilter.h>
#include <juce_core/javascript/juce_Javascript.h>
#include <juce_core/javascript/juce_JSON.h>

#include <juce_core/logging/juce_FileLogger.h>
#include <juce_core/logging/juce_Logger.h>
#include <juce_core/maths/juce_BigInteger.h>
#include <juce_core/maths/juce_Expression.h>
#include <juce_core/maths/juce_MathsFunctions.h>
#include <juce_core/maths/juce_NormalisableRange.h>
#include <juce_core/maths/juce_Random.h>
#include <juce_core/maths/juce_Range.h>
#include <juce_core/maths/juce_StatisticsAccumulator.h>
#include <juce_core/memory/juce_AllocationHooks.h>
#include <juce_core/memory/juce_Atomic.h>
#include <juce_core/memory/juce_ByteOrder.h>
#include <juce_core/memory/juce_ContainerDeletePolicy.h>
#include <juce_core/memory/juce_HeapBlock.h>
#include <juce_core/memory/juce_HeavyweightLeakedObjectDetector.h>
#include <juce_core/memory/juce_LeakedObjectDetector.h>
#include <juce_core/memory/juce_Memory.h>
#include <juce_core/memory/juce_MemoryBlock.h>
#include <juce_core/memory/juce_OptionalScopedPointer.h>
#include <juce_core/memory/juce_ReferenceCountedObject.h>
#include <juce_core/memory/juce_Reservoir.h>
#include <juce_core/memory/juce_ScopedPointer.h>
#include <juce_core/memory/juce_SharedResourcePointer.h>
#include <juce_core/memory/juce_Singleton.h>
#include <juce_core/memory/juce_WeakReference.h>
#include <juce_core/misc/juce_ConsoleApplication.h>
#include <juce_core/misc/juce_Functional.h>
#include <juce_core/misc/juce_Result.h>
#include <juce_core/misc/juce_RuntimePermissions.h>
#include <juce_core/misc/juce_Uuid.h>
#include <juce_core/misc/juce_WindowsRegistry.h>

#include <juce_core/network/juce_IPAddress.h>
#include <juce_core/network/juce_MACAddress.h>
#include <juce_core/network/juce_NamedPipe.h>
#include <juce_core/network/juce_Socket.h>
#include <juce_core/network/juce_URL.h>
#include <juce_core/network/juce_WebInputStream.h>
#include <juce_core/streams/juce_AndroidDocumentInputSource.h>
#include <juce_core/streams/juce_BufferedInputStream.h>
#include <juce_core/streams/juce_FileInputSource.h>
#include <juce_core/streams/juce_InputSource.h>
#include <juce_core/streams/juce_InputStream.h>
#include <juce_core/streams/juce_MemoryInputStream.h>
#include <juce_core/streams/juce_MemoryOutputStream.h>
#include <juce_core/streams/juce_OutputStream.h>
#include <juce_core/streams/juce_SubregionStream.h>
#include <juce_core/streams/juce_URLInputSource.h>
#include <juce_core/system/juce_CompilerSupport.h>
#include <juce_core/system/juce_CompilerWarnings.h>
#include <juce_core/system/juce_PlatformDefs.h>
#include <juce_core/system/juce_StandardHeader.h>
#include <juce_core/system/juce_SystemStats.h>
#include <juce_core/system/juce_TargetPlatform.h>
#include <juce_core/text/juce_Base64.h>
#include <juce_core/text/juce_CharacterFunctions.h>
#include <juce_core/text/juce_CharPointer_ASCII.h>
#include <juce_core/text/juce_CharPointer_UTF16.h>
#include <juce_core/text/juce_CharPointer_UTF32.h>
#include <juce_core/text/juce_CharPointer_UTF8.h>
#include <juce_core/text/juce_Identifier.h>
#include <juce_core/text/juce_LocalisedStrings.h>
#include <juce_core/text/juce_NewLine.h>
#include <juce_core/text/juce_String.h>
#include <juce_core/text/juce_StringArray.h>
#include <juce_core/text/juce_StringPairArray.h>
#include <juce_core/text/juce_StringPool.h>
#include <juce_core/text/juce_StringRef.h>
#include <juce_core/text/juce_TextDiff.h>
#include <juce_core/text/juce_NumbersToStringConverter.h>
#include <juce_core/threads/juce_ChildProcess.h>
#include <juce_core/threads/juce_CriticalSection.h>
#include <juce_core/threads/juce_DynamicLibrary.h>
#include <juce_core/threads/juce_HighResolutionTimer.h>
#include <juce_core/threads/juce_InterProcessLock.h>
#include <juce_core/threads/juce_Process.h>
#include <juce_core/threads/juce_ReadWriteLock.h>
#include <juce_core/threads/juce_ScopedLock.h>
#include <juce_core/threads/juce_ScopedReadLock.h>
#include <juce_core/threads/juce_ScopedWriteLock.h>
#include <juce_core/threads/juce_SpinLock.h>
#include <juce_core/threads/juce_Thread.h>
#include <juce_core/threads/juce_ThreadLocalValue.h>
#include <juce_core/threads/juce_ThreadPool.h>
#include <juce_core/threads/juce_TimeSliceThread.h>
#include <juce_core/threads/juce_WaitableEvent.h>
#include <juce_core/time/juce_PerformanceCounter.h>
#include <juce_core/time/juce_RelativeTime.h>
#include <juce_core/time/juce_Time.h>
#include <juce_core/unit_tests/juce_UnitTest.h>
#include <juce_core/unit_tests/juce_UnitTestCategories.h>
#include <juce_core/xml/juce_XmlDocument.h>
#include <juce_core/xml/juce_XmlElement.h>
#include <juce_core/zip/juce_GZIPCompressorOutputStream.h>
#include <juce_core/zip/juce_GZIPDecompressorInputStream.h>
