add_subdirectory(plugin_110_AaronStaticModules)
add_subdirectory(plugin_111_AZ)
add_subdirectory(plugin_112_PachdeHcOne)
add_subdirectory(plugin_113_PdArray)
add_subdirectory(plugin_114_PitchGridRack)
add_subdirectory(plugin_115_QuestionableModules)
add_subdirectory(plugin_116_rchoices)
add_subdirectory(plugin_117_SqHarmony)
add_subdirectory(plugin_118_SS_Modules)
add_subdirectory(plugin_119_ScannerDarkly)
