add_subdirectory(plugin_100_docB)
add_subdirectory(plugin_101_Autinn)
add_subdirectory(plugin_102_KilpatrickToolbox)
add_subdirectory(plugin_103_MockbaModular)
add_subdirectory(plugin_104_modular80)
add_subdirectory(plugin_105_MrLumps)
add_subdirectory(plugin_106_NotThings)
add_subdirectory(plugin_107_OkaySynthesizer)
add_subdirectory(plugin_108_UZZ)
add_subdirectory(plugin_109_Vostok)
# add_subdirectory(plugin_110_Atelier)
