add_subdirectory(signalsmith_audio2wav)
# add_subdirectory(signalsmith_dsp_benchmarks)
# add_subdirectory(signalsmith_dsp_tests)
add_subdirectory(signalsmith_dsp_util)
add_subdirectory(signalsmith_elliptic_blep)
add_subdirectory(signalsmith_pitchtime_cmd)
add_subdirectory(signalsmith_pitchtime)
add_subdirectory(signalsmith_plot)
add_subdirectory(signalsmith_reverb)
add_subdirectory(signalsmith_hilbert)
add_subdirectory(signalsmith_linear)
