add_subdirectory(de-rack2-fuzzysearchdatabase)
add_subdirectory(de-rack2-speexdsp)
add_subdirectory(libRack2)
add_subdirectory(Rack2)
add_subdirectory(libEuroRack)
# add_subdirectory(_plugins1)
# add_subdirectory(_plugins2)
# add_subdirectory(_plugins3)
# add_subdirectory(_plugins4)
# add_subdirectory(_plugins5)
# add_subdirectory(_plugins6)
# add_subdirectory(_plugins7)
# add_subdirectory(_plugins8)
add_subdirectory(Surge-rack)
