add_subdirectory(sfml_demo_event_handling)
add_subdirectory(sfml_demo_island)
add_subdirectory(sfml_demo_joystick)
add_subdirectory(sfml_demo_opengl)
add_subdirectory(sfml_demo_raw_input)
add_subdirectory(sfml_demo_shader)
add_subdirectory(sfml_demo_stencil)
add_subdirectory(sfml_demo_text)
add_subdirectory(sfml_demo_vulkan)
add_subdirectory(sfml_demo_win32)