# # Geometry, physics, boost, CGAL, OpenSCAD
# add_subdirectory(_libassimp)
# add_subdirectory(_libcad)
# #add_subdirectory(de-ode-0.16.5)

add_subdirectory(de-catch)
add_subdirectory(de-catch2)
add_subdirectory(de-clara)
# add_subdirectory(de-cpuid)

# GUI
# add_subdirectory(de-fltk-1.3.5)
# add_subdirectory(de-wx-3.1.5)

# # Audio, FFMPEG, MIDI, TAGS, FMOD, FFTs, VST-Plugin SDK, Juce
# add_subdirectory(_libaudio)

add_subdirectory(de-lua-5.4.7)
# add_subdirectory(de-ginac)


# Introduced by Rack2
add_subdirectory(de-jansson-json)
add_subdirectory(de-ghc-filesystem)
add_subdirectory(de-osdialog)
add_subdirectory(de-pffft)
add_subdirectory(de-tinyexpr)


# Geometry, physics, boost, CGAL, OpenSCAD
#add_subdirectory(_libassimp)
#add_subdirectory(_libcad)
#add_subdirectory(de-ode-0.16.5)

# GUI
#add_subdirectory(de-fltk-1.3.5)
#add_subdirectory(de-wx-3.1.5)

# Internet
#add_subdirectory(de-enet-1.3.18)
# Audio, FFMPEG, MIDI, TAGS, FMOD, FFTs, VST-Plugin SDK, Juce
#add_subdirectory(_libaudio)

#add_subdirectory(de-lua-5.4.7)
#add_subdirectory(de-sqlite3)
# add_subdirectory(de-ginac)
