# CMake generated Testfile for 
# Source directory: C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0
# Build directory: C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(roundtrip/c/enc/encode.c/1 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=1" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/enc/encode.c" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/encode.c.1" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/1 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/6 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=6" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/enc/encode.c" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/encode.c.6" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/6 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/9 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=9" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/enc/encode.c" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/encode.c.9" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/9 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/11 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=11" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/enc/encode.c" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/encode.c.11" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/11 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/1 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=1" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/common/dictionary.h" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/dictionary.h.1" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/1 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/6 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=6" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/common/dictionary.h" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/dictionary.h.6" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/6 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/9 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=9" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/common/dictionary.h" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/dictionary.h.9" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/9 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/11 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=11" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/common/dictionary.h" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/dictionary.h.11" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/11 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/1 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=1" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/dec/decode.c" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/decode.c.1" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/1 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/6 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=6" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/dec/decode.c" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/decode.c.6" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/6 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/9 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=9" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/dec/decode.c" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/decode.c.9" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/9 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/11 "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DQUALITY=11" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/c/dec/decode.c" "-DOUTPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/decode.c.11" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/11 PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;239;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(compatibility/tests/testdata/empty.compressed "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/testdata/empty.compressed" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-compatibility-test.cmake")
set_tests_properties(compatibility/tests/testdata/empty.compressed PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;260;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
add_test(compatibility/tests/testdata/ukkonooa.compressed "C:/sdk/cmake-3.29.0/bin/cmake.exe" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/benni/brotli.exe" "-DINPUT=C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/testdata/ukkonooa.compressed" "-P" "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/tests/run-compatibility-test.cmake")
set_tests_properties(compatibility/tests/testdata/ukkonooa.compressed PROPERTIES  _BACKTRACE_TRIPLES "C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;260;add_test;C:/sdk/msys64/home/firestarter/brotli-v1.1.1-rc0/CMakeLists.txt;0;")
