add_subdirectory(plugin_01_Fundamental)
add_subdirectory(plugin_02_Gemini)
add_subdirectory(plugin_03_MADZINE)
add_subdirectory(plugin_04_CVfunk-Modules)
# add_subdirectory(plugin_05_AudibleInstruments-2)
add_subdirectory(plugin_06_Geodesics)
add_subdirectory(plugin_07_Sapphire)
add_subdirectory(plugin_08_JulioChaos)
add_subdirectory(plugin_09_LOGinstruments)
add_subdirectory(plugin_10_MSM)
add_subdirectory(plugin_11_AmbushedCat)
add_subdirectory(plugin_12_TeknoLogical)
add_subdirectory(plugin_13_Nozori)
add_subdirectory(plugin_14_ArhythmeticUnits-Fourier)
add_subdirectory(plugin_15_Bogaudio)

