add_subdirectory(plugin_90_HamptonHarmonics)
add_subdirectory(plugin_91_DanielDavies)
add_subdirectory(plugin_92_RareBreeds)
add_subdirectory(plugin_93_Visions)
add_subdirectory(plugin_94_Sulamith)
add_subdirectory(plugin_95_ZZC)
add_subdirectory(plugin_96_Tyche)
add_subdirectory(plugin_97_TrowaSoft)
# add_subdirectory(plugin_98_PatchableDevices)
add_subdirectory(plugin_99_SynthKit)
