add_subdirectory(plugin_80_21kHz)
add_subdirectory(plugin_81_CatroModulo)
add_subdirectory(plugin_82_Holon)
add_subdirectory(plugin_83_Little-Utils)
add_subdirectory(plugin_84_JW-Modules)
add_subdirectory(plugin_85_mahlenmorris)
add_subdirectory(plugin_86_Noise86)
add_subdirectory(plugin_87_AnimatedCircuits)
add_subdirectory(plugin_88_GP)
add_subdirectory(plugin_89_NocturnalEncoder)
