if (NOT BUILD_SHARED_LIBS)
    if (MSVC)
    else()
        target_compile_options(${APP_NAME} PRIVATE -Wno-unused-command-line-argument)
		target_compile_options(${APP_NAME} PRIVATE -static)
		target_compile_options(${APP_NAME} PRIVATE -static-libstdc++)
		target_compile_options(${APP_NAME} PRIVATE -static-libgcc)
		target_link_options(${APP_NAME} PRIVATE -static)
		target_link_options(${APP_NAME} PRIVATE -static-libstdc++)
		target_link_options(${APP_NAME} PRIVATE -static-libgcc)
		# message("${APP_NAME} will link statically to GNU runtime.")
	endif()
endif()