add_subdirectory(de-resample)
add_subdirectory(de-oscpack)
add_subdirectory(de-OpenSimplexNoise)

add_subdirectory(de-midifile)
add_subdirectory(de-open303-code)
add_subdirectory(de-fmt)
add_subdirectory(de-sst-basic-blocks)
add_subdirectory(de-sst-rackhelpers)

add_subdirectory(de-eurorack)

add_subdirectory(de-DaisySP)