//! This file is autogenerated by assets/graphics/create_graphics_headers.sh
//! Do not edit this by hand

#pragma once

#include "../GlobalIncludes.h"

struct UIAssetsData {
    static std::array<const uint8_t*, 1248> Data;
};
